name: Build tests-sbc Docker images

on: [push]

env:
  IMAGE_NAME: tests-sbc

jobs:
  build:
    name: build tests-sbc
    runs-on: [self-hosted, heavy-build]
    strategy:
      fail-fast: false
      matrix:
        IMAGE_TAG: [11-22.04, 13-24.04]
    steps:
      - uses: actions/checkout@v4
      - name: docker build
        uses: ./.github/actions/docker-build
        with:
          image: ${{ env.IMAGE_NAME }}
          tag: ${{ matrix.IMAGE_TAG }}
          platform: linux/arm64
          workdir: ${{ env.IMAGE_NAME }}/${{ matrix.IMAGE_TAG }}
          extraBuildArgs: --pull

  deploy:
    name: deploy tests-sbc
    runs-on: [self-hosted, heavy-build]
    if: github.ref_name == 'main'
    needs: build
    strategy:
      matrix:
        IMAGE_TAG: [11-22.04, 13-24.04]
    steps:
      - name: docker push
        uses: ./.github/actions/docker-push
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          image: ${{ env.IMAGE_NAME }}
          tag: ${{ matrix.IMAGE_TAG }}
